version: "3.8"

services:
  watcher:
    build:
      context: .
      dockerfile: Dockerfile
    image: node_watch:latest
    container_name: node_watch
    restart: unless-stopped

    # Bind‐mount the host's Docker socket so the watcher can inspect/restart containers.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./restart_logs:/app/restart.logs
      - ./watcher.log:/app/watcher.log
      - ./:/app
    tty: true  


    # The watcher script itself prints to stdout. If you want to see tlogs:
    # docker-compose logs -f watcher
